// Command generate-community-files generates the org community-health files
// under .github/ from canonical sources under src/.
//
// The files GitHub consumes directly — the pull request template and the issue
// forms — are GENERATED so each instruction has a single source of truth. Edit
// the source, then re-run to re-sync the generated copies. CI runs it with
// --check to verify they match.
//
// Run it from the repo root (the Taskfile does this):
//
//	go run ./scripts/generate-community-files.go            # write outputs
//	go run ./scripts/generate-community-files.go --check    # verify; exit 1 if stale
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const generator = "scripts/generate-community-files.go"

// mapping pairs each canonical source with its generated output, relative to
// the repo root.
var mapping = []struct{ src, dst string }{
	{"src/pull_request.md", ".github/PULL_REQUEST_TEMPLATE.md"},
	{"src/issue-defect.yml", ".github/ISSUE_TEMPLATE/1-defect.yml"},
	{"src/issue-feature.yml", ".github/ISSUE_TEMPLATE/2-feature.yml"},
	{"src/issue-task.yml", ".github/ISSUE_TEMPLATE/3-task.yml"},
}

// header returns a Go-style "Code generated ... DO NOT EDIT." banner in the
// comment syntax for the file type.
func header(srcRel string) string {
	msg := fmt.Sprintf("Code generated by %s from %s; DO NOT EDIT.", generator, srcRel)
	if strings.HasSuffix(srcRel, ".md") {
		return fmt.Sprintf("<!-- %s -->\n\n", msg)
	}
	// Hash-comment style for YAML (and anything else).
	return fmt.Sprintf("# %s\n\n", msg)
}

func render(srcRel string) (string, error) {
	b, err := os.ReadFile(srcRel)
	if err != nil {
		return "", err
	}
	return header(srcRel) + string(b), nil
}

func main() {
	check := false
	for _, a := range os.Args[1:] {
		if a == "--check" {
			check = true
		}
	}

	var stale []string
	for _, m := range mapping {
		expected, err := render(m.src)
		if err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			os.Exit(2)
		}
		current, err := os.ReadFile(m.dst)
		if err == nil && string(current) == expected {
			continue
		}
		if check {
			stale = append(stale, m.dst)
			continue
		}
		if err := os.MkdirAll(filepath.Dir(m.dst), 0o755); err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			os.Exit(2)
		}
		if err := os.WriteFile(m.dst, []byte(expected), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			os.Exit(2)
		}
		fmt.Println("wrote", m.dst)
	}

	if check {
		if len(stale) > 0 {
			fmt.Println("Generated files are out of sync with src/:")
			for _, s := range stale {
				fmt.Println("  -", s)
			}
			fmt.Println("Run: task generate")
			os.Exit(1)
		}
		fmt.Println("All generated files are in sync.")
	}
}
